apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: qotd-build-and-deploy
spec:
  pipelineRef:
    name: qotd-build-and-deploy
  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
